  CREATE TABLE USERS(
  id INTEGER NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  followers INTEGER NOT NULL,
  following  INTEGER NOT NULL,
  accountID VARCHAR(50) PRIMARY KEY NOT NULL
  );
  
  
  CREATE TABLE FOLLOWERS(
  id INTEGER NOT NULL AUTO_INCREMENT,
  followersID VARCHAR(50) NOT NULL,
  accountID VARCHAR(50) NOT NULL,
  FOREIGN KEY(accountID) REFERENCES USERS(accountID)
  );
  
  CREATE TABLE TWEETS(
  id INTEGER NOT NULL AUTO_INCREMENT,
  tweet VARCHAR(100) NOT NULL,
  accountID VARCHAR(50),
  FOREIGN KEY(accountID) REFERENCES USERS(accountID)
  );
  
  
  CREATE TABLE TWEETS_REPLIES(
  id INTEGER NOT NULL AUTO_INCREMENT,
  tweet VARCHAR(100) NOT NULL,
  accountID VARCHAR(50),
  tweetID INTEGER NOT NULL,
  FOREIGN KEY(accountID) REFERENCES USERS(accountID),
  FOREIGN KEY(tweetID) REFERENCES TWEETS(id)
  );
  